SIMPLE_VAR = heyo
SIMPLE_VAR_COMMENT = the comment is gone
SPACES_BEFORE_TAB =  	    var_beginning>var_end

sparse_rule: depa depb

	command 1

	command 2

 B 	 =  	 B_var_beginning	  B_var_end

packed_rule: depa depb
	 command 1
	command 2

silent_rule: depa depb
	    @  command 1
	@command 2

rule_comment: depa depb 

command_space_rule: depa depb
	     echo spaces before
	echo spaces after
	echo this is a

simple_rule: simple_dep

no_dep_rule:

variable_rule: beginning $(SIMPLE_VAR_COMMENT) end
	echo "shouldn't be expanded: $(SIMPLE_VAR_COMMENT)"
